name: Deploy pipeline

on: 
  push: 
    branches:
      - "master"

jobs: 
  deploy: 
    runs-on: ubuntu-20.04
    steps:
      # - name: cancel redundant build
      #   uses: styfle/cancel-workflow-action0.9.1
      #   with:
      #     access_token: ${{ github.token }}


      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: prueba
        env: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
        run: echo  $host

      - name: Build
        uses: appleboy/ssh-action@v0.1.2
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            pm2 stop ednapi