name: Deploy pipeline

on: 
  push: 
    branches:
      - "master"

jobs: 
  deploy: 
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - name: ssh con 
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with: 
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          pass: ${{ secrets.KEY }}
          connect_timeout: 10s
          script: |
            cd ${{ secrets.PATH }}
            git checkout .
            git pull
            npm run build
            pm2 reload ednapi