name: Deploy pipeline

on: 
  push: 
    branches:
      - "master"

jobs: 
  deploy: 
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - name: push to server
        uses: jjst/action-digitalocean-deploy-app@v2
        with: 
          token: ${{secrets.TOKEN}}
          app-id: edn-api
          script: |
            cd ${{secrets.PATH}}
            git checkout .
            git pull
            npm run build
            pm2 reload ednapi